# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    reviewers:
      - "JasonRobertDestiny"
    assignees:
      - "JasonRobertDestiny"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    # Batch update strategy
    groups:
      fastapi-group:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "pydantic*"
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black*"
          - "flake8*"
    # Version update limits
    open-pull-requests-limit: 5
    
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Shanghai"
    reviewers:
      - "JasonRobertDestiny"
    labels:
      - "github-actions"
      - "automated"
    open-pull-requests-limit: 3

  # Docker dependencies (if Dockerfile exists)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    reviewers:
      - "JasonRobertDestiny"
    labels:
      - "docker"
      - "automated"
    open-pull-requests-limit: 2
