id: PM-2025-017
created_at: '2026-01-13T05:57:58.465498Z'
source_commit: 19f9e93
severity: medium
title: 修复变量命名冲突导致的flake8 F823错误
description: 在meetspot_recommender.py中，变量命名冲突导致flake8 F823错误，影响GitHub Actions CI的正常运行。
root_cause: 局部变量名与导入模块名冲突，导致变量在赋值前被引用。
triggers:
  files:
  - app/tool/*.py
  functions:
  - CafeRecommender
  patterns:
  - local variable 'html' referenced before assignment
  keywords:
  - flake8
  - F823
  - 命名冲突
  - html
fix_pattern:
  approach: 重命名冲突变量以避免与导入模块名重复。
  key_changes:
  - 将变量名从`html`改为`html_content`
verification:
- 确保变量名与导入模块名不冲突
- 运行flake8检查确保无F823错误
- 验证GitHub Actions CI通过
related:
  files_changed:
  - app/tool/meetspot_recommender.py
tags:
- ci
- linting
- python
