id: PM-2025-006
created_at: '2026-01-13T05:57:10.607031Z'
source_commit: b6831e5
severity: medium
title: 地图标记添加位置名称标签修复
description: 地图标记未显示位置名称标签，导致用户无法直观识别标记位置。此问题影响用户体验，尤其是在多个标记密集的情况下。
root_cause: 地图标记未包含位置名称标签的渲染逻辑。
triggers:
  files:
  - app/tool/*.py
  functions:
  - CafeRecommender
  patterns:
  - 'markerContent = `<div style="background-color: \${{color}};'
  keywords:
  - map
  - marker
  - label
  - 位置名称
fix_pattern:
  approach: 为地图标记添加位置名称标签，并调整样式以提高可读性。
  key_changes:
  - 为中心点和用户位置标记添加标签显示逻辑
  - 调整标签样式，包括背景色、阴影和字体
verification:
- 检查地图标记是否正确显示位置名称标签
- 验证标签样式是否符合设计规范
- 确保其他标记（如场所标记）未受影响
related:
  files_changed:
  - app/tool/meetspot_recommender.py
tags:
- ui
- map
- label
- user experience
